#!/bin/bash
#
# ufetch - tiny system info for Debian
#

## INFO

# user is already defined
# hostname is already defined
OS=$1
KERNEL=$(uname -rs)
UPTIME=$(uptime -p | sed s:"up ":"":)
if [ "$1" == "Debian" ];
then
    PACKAGES=$(dpkg --get-selections | wc -l)
# shell is already defined
WM=$(tail -n 1 "$HOME/.xinitrc" | cut -d " " -f2)
WEBSITE=$2

## DEFINE COLORS

rc=$(tput sgr0)		# reset
c0=$(tput setaf 0)	# black
c1=$(tput setaf 1)	# red
c2=$(tput setaf 2)	# green
c3=$(tput setaf 3)	# yellow
c4=$(tput setaf 4)	# blue
c5=$(tput setaf 5)	# magenta
c6=$(tput setaf 6)	# cyan
c7=$(tput setaf 7)	# white
bc=$(tput bold)		# bold

## OUTPUT
# todo: make good


echo "${c6}      ___     ${bc}${USER}${c7}@${c6}${HOSTNAME}${rc}"
echo "${c6}     (${c7}.· ${c6}|    ${bc}OS:        ${c7}${OS}${rc}"
echo "${c6}     (${c3}<> ${c6}|    ${bc}KERNEL:    ${c7}${KERNEL}${rc}"
echo "${c6}    / ${c7}__  ${c6}\\   ${bc}UPTIME:    ${c7}${UPTIME}${rc}"
echo "${c6}   ( ${c7}/  \ ${c6}/|  ${bc}PACKAGES:  ${c7}${PACKAGES}${rc}"
echo "${c3}  _${c6}/\ ${c7}__)${c6}/${c3}_${c6})  ${bc}SHELL:     ${c7}${SHELL}${rc}"
echo "${c3}  \/${c6}-____${c3}\/   ${c6}${bc}WM:        ${c7}${WM}${rc}"
if [ -n ${WEBSITE} ] 
then
echo "             ${c6} ${bc}WEBSITE:   ${c7}${WEBSITE}${rc}"
fi

